source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Popover_Example', :exclusive => true do
  pod "Popover", :path => "../"
end

target 'Popover_Tests', :exclusive => true do
  pod "Popover", :path => "../"

  pod 'FBSnapshotTestCase'
end
